# Netlify Build & Redirect Configuration

[build]
  # Build command for your Vite project
  command = "npm run build"
  
  # The directory that contains your built site (for Vite, it's 'dist')
  publish = "dist"
  
  # --- FIX: Tell Netlify your project is in the 'my-portfolio' folder ---
  base = "my-portfolio"

# Redirect rule for Single Page Applications (SPA)
# This rule ensures that all paths are sent to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
