# Netlify configuration file

[build]
  # Build command for your Vite project
  command = "npm run build"
  
  # The directory that contains the built site
  publish = "dist"

# Redirect rule for Single Page Applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
